[green_agent]
image= "ghcr.io/hashiru-ai/naamse-naamse-green-agent:latest"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
image = "ghcr.io/hashiru-ai/naamse-naamse-purple-agent:latest"
name = "agent"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }

[config]
iterations_limit = 3
mutations_per_iteration = 3
score_threshold = 50