[green_agent]
agentbeats_id = ""
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "defender"
env = {}

[config]
# Add your assessment config here
